[features]
seeds = false
skip-lint = false
[programs.localnet]
multi_level_squads = "C4m1216wrXuhEQ7FqoN7ySF5qeZLfrEyYtxfYCEYCkKU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dhruvraj/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
